name: dialect-bias
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy=1.26.4
  - pandas=2.2.2
  - attrs
  - packaging
  - click
  - certifi
  - cachetools
  - charset-normalizer
  - idna
  - pyparsing
  - python-dateutil
  - pytz
  - requests
  - typing_extensions
  - six
  - pip:
      - google-api-python-client>=2.100
      - google-auth>=2.25
      - google-auth-httplib2>=0.2
      - google-auth-oauthlib>=1.0
      - googleapis-common-protos>=1.63
      - httplib2>=0.22
      - jiwer>=3.0
      - oauthlib>=3.2
      - outcome>=1.2
      - proto-plus>=1.22
      - protobuf==4.25.3
      - pyasn1>=0.5
      - pyasn1_modules>=0.3
      - python-dotenv>=1.0
      - rapidfuzz>=3.0
      - requests-oauthlib>=2.0
      - rsa>=4.8
      - selenium>=4.20
      - sniffio>=1.3
      - sortedcontainers>=2.4
      - srt>=3.5
      - trio>=0.25
      - trio-websocket>=0.11
      - uritemplate>=4.1
      - urllib3>=2.2
      - webdriver-manager>=4.0
      - websocket-client>=1.8
      - webvtt-py>=0.5
      - wsproto>=1.2
      - youtube-dl==2021.12.17
